/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanwei_Native_EventSendClassNative */

#ifndef _Included_com_hanwei_Native_EventSendClassNative
#define _Included_com_hanwei_Native_EventSendClassNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hanwei_Native_EventSendClassNative
 * Method:    jni_CreateObj
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_hanwei_Native_EventSendClassNative_jni_1CreateObj
  (JNIEnv *, jclass);

/*
 * Class:     com_hanwei_Native_EventSendClassNative
 * Method:    jni_DeleteObj
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hanwei_Native_EventSendClassNative_jni_1DeleteObj
  (JNIEnv *, jclass, jlong);


/*
* Class:     com_hanwei_Native_EventSendClassNative
* Method:    GetSendEvent1
* Signature: (J)J
*/
JNIEXPORT jlong JNICALL Java_com_hanwei_Native_EventSendClassNative_GetSendEvent1
(JNIEnv *, jclass, jlong);

/*
* Class:     com_hanwei_Native_EventSendClassNative
* Method:    GetSendEvent2
* Signature: (J)J
*/
JNIEXPORT jlong JNICALL Java_com_hanwei_Native_EventSendClassNative_GetSendEvent2
(JNIEnv *, jclass, jlong);

/*
 * Class:     com_hanwei_Native_EventSendClassNative
 * Method:    SendEvent1
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hanwei_Native_EventSendClassNative_SendEvent1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_hanwei_Native_EventSendClassNative
 * Method:    SendEvent2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hanwei_Native_EventSendClassNative_SendEvent2
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
