/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanwei_Native_EventArgsNative */

#ifndef _Included_com_hanwei_Native_EventArgsNative
#define _Included_com_hanwei_Native_EventArgsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hanwei_Native_EventArgsNative
 * Method:    jni_CreateObj
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_hanwei_Native_EventArgsNative_jni_1CreateObj
  (JNIEnv *, jclass);

/*
 * Class:     com_hanwei_Native_EventArgsNative
 * Method:    jni_DeleteObj
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_hanwei_Native_EventArgsNative_jni_1DeleteObj
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
